version: '2.2'

services:
  webinar-nginx:
    image: mackedonsky/webinar:webinar-nginx
    container_name: webinar-nginx
    restart: always
    cpu_count: 1
    mem_limit: 1G
    ports:
      - '80:80'
    volumes:
      - /opt/webinar-app:/home/aurora/app
      - /opt/webinar-nginx/:/etc/nginx/sites-enabled
    networks:
      webinar_net:
        ipv4_address: 172.19.0.2

  backend-db3:
    image: mysql:5.7
    container_name: webinar3-mysql
    restart: always
    cpu_count: 1
    mem_limit: 1G
    command: --init-file ${WEBINAR_INIT}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${WEBINAR_DUMP}:${WEBINAR_INIT}
      - ${WEBINAR_DATA}webinar3:${MYSQL_DATA}
    networks:
      webinar_net:
        ipv4_address: 172.19.0.3

  backend-db4:
    image: mysql:5.7
    container_name: webinar4-mysql
    restart: always
    cpu_count: 1
    mem_limit: 1G
    command: --init-file ${WEBINAR_INIT}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${WEBINAR_DUMP}:${WEBINAR_INIT}
      - ${WEBINAR_DATA}webinar4:${MYSQL_DATA}
    networks:
      webinar_net:
        ipv4_address: 172.19.0.4

  backend-db5:
    image: mysql:5.7
    container_name: webinar5-mysql
    restart: always
    cpu_count: 1
    mem_limit: 1G
    command: --init-file ${WEBINAR_INIT}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${WEBINAR_DUMP}:${WEBINAR_INIT}
      - ${WEBINAR_DATA}webinar5:${MYSQL_DATA}
    networks:
      webinar_net:
        ipv4_address: 172.19.0.5


networks:
  webinar_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.19.0.0/24"
    driver_opts:
      com.docker.network.bridge.name: webinar_mysql

