---

- name: Create directory if they don't exist
  tags: webinar, webinar_create
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /opt/webinar-nginx
    - /opt/webinar-mysql/dump
    - /opt/webinar-bastion

- name: Create app directory
  tags: webinar, webinar_create
  file:
    path: '/opt/webinar-app'
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Copy frontend app
  tags: webinar, webinar_create
  template:
    src: "templates/wsgiapp.py.j2"
    dest: "/opt/webinar-app/wsgiapp.py"
    owner: 'www-data'
    group: 'www-data'
    mode: '0755'

- name: Copy dump
  tags: webinar, webinar_create
  template:
    src: "templates/webinar.sql.j2"
    dest: "/opt/webinar-mysql/dump/webinar.sql"
    owner: root
    group: root
    mode: 0644

- name: Copy nginx config
  tags: webinar, webinar_create
  copy:
    src: "files/webinar_nginx"
    dest: "/opt/webinar-nginx/webinar"
    owner: root
    group: root
    mode: 0644
