---

- name: Create directory if they don't exist
  tags: webinar, webinar_create
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - path: /opt/webinar-app
      owner: 'www-data'
      group: 'www-data'
      mode: '0600'
    - path: /opt/webinar-nginx
    - path: /opt/webinar-mysql/dump
    - path: /opt/webinar-bastion

- name: Copy frontend app
  tags: webinar, webinar_create
  template:
    src: "templates/wsgiapp.py.j2"
    dest: "/opt/webinar-app/wsgiapp.py"
    owner: 'www-data'
    group: 'www-data'
    mode: '0600'

- name: Copy dump
  tags: webinar, webinar_create
  copy:
    src: "files/webinar.sql"
    dest: "/opt/webinar-mysql/dump/"
    owner: root
    group: root
    mode: 0644

- name: Copy nginx config
  tags: webinar, webinar_create
  copy:
    src: "files/webinar_nginx"
    dest: "/opt/webinar-nginx/webinar"
    owner: root
    group: root
    mode: 0644
